# Generated by Django 5.2.5 on 2026-03-17 00:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_producto_stock_vendido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=30, unique=True)),
                ('cliente', models.CharField(max_length=180)),
                ('fecha_venta', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada'), ('REEMBOLSADA', 'Reembolsada')], default='PENDIENTE', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('MERCADO_PAGO', 'Mercado Pago'), ('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta')], default='MERCADO_PAGO', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('referencia_externa', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mp_preference_id', models.CharField(blank=True, default='', max_length=120)),
                ('mp_payment_id', models.CharField(blank=True, default='', max_length=120)),
                ('mp_status', models.CharField(blank=True, default='', max_length=60)),
                ('mp_status_detail', models.CharField(blank=True, default='', max_length=120)),
                ('mp_raw', models.JSONField(blank=True, default=dict)),
                ('inventario_descontado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ventas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'db_table': 'ventas_detalles',
                'ordering': ['id'],
            },
        ),
    ]
