# Generated by Django 5.2.5 on 2026-03-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='venta',
            name='codigo_postal',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='direccion_linea1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='direccion_linea2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_direccion',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado_envio',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('EN_PROCESO', 'En proceso de envío'), ('ENVIADO', 'Enviado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='referencias_envio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='color',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='talla',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
