# Generated by Django 5.2.5 on 2026-03-19 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_ciudad_venta_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
