# Generated by Django 5.2.5 on 2026-03-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_vendido',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
