# Generated by Django 5.2.5 on 2026-03-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_stock_vendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='permite_compra',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_rebaja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
