# Generated by Django 5.2.5 on 2026-04-09 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('activo', models.BooleanField(default=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('token_version', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ClienteDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, default='', max_length=80)),
                ('destinatario', models.CharField(blank=True, default='', max_length=180)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('direccion_linea1', models.CharField(max_length=255)),
                ('direccion_linea2', models.CharField(blank=True, default='', max_length=255)),
                ('ciudad', models.CharField(max_length=120)),
                ('estado_direccion', models.CharField(max_length=120)),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=20)),
                ('referencias_envio', models.TextField(blank=True, default='')),
                ('principal', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='clientes.cliente')),
            ],
            options={
                'db_table': 'clientes_direcciones',
                'ordering': ['-principal', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClienteTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('MERCADO_PAGO', 'Mercado Pago')], default='MERCADO_PAGO', max_length=40)),
                ('titular', models.CharField(blank=True, default='', max_length=180)),
                ('marca', models.CharField(blank=True, default='', max_length=50)),
                ('ultimos4', models.CharField(max_length=4)),
                ('mes_expiracion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('anio_expiracion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mp_customer_id', models.CharField(blank=True, default='', max_length=120)),
                ('mp_card_id', models.CharField(blank=True, default='', max_length=120)),
                ('principal', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='clientes.cliente')),
            ],
            options={
                'db_table': 'clientes_tarjetas',
                'ordering': ['-principal', '-id'],
                'unique_together': {('cliente', 'mp_card_id')},
            },
        ),
    ]
